---
title: "Data"
output: 
  html_document:
    theme: cerulean
---

### Occupational Information Network (O*NET)

[Occupational Information Network (O*NET)](https://www.onetonline.org/) is an online database that provides information on occupations and is a resource to job seekers and vetrans who are looking for work. O*NET produced a [crosswalk](https://www.onetcenter.org/crosswalks.html) of Army Jobs and Standard Occupation Classification (SOC) Codes. SOC codes are a federal standardization of jobs that helps classify occupational data. [This crosswalk was produced to connect the 10 largest Army jobs, commonly referred to as military occupational specialties (MOS), to civilian skills](https://www.rand.org/pubs/research_reports/RR1719.html). This was a way of understanding which civilian occupations prepared individuals to best perform in these 10 Army jobs. This is a part of larger works on veteran transitions from the military to civilian life.

### Burning Glass

[Burning Glass](https://www.burning-glass.com/) data is proprietary data source which scrapes job advertisments and resumes to create panel data on jobs. This data sourice provided us with skills that are listed on job advertisements across multiple SOC cpdodes. For each SOC code there are types of skills required for jobs and therefore when attaching these skills to SOC codes that similar to Army jobs we're able to create a vector of skills gained within the Army that they could use for their resumes.

### Bureau of Labor Statistics

[Bureau of Labor Statistics (BLS)](https://www.bls.gov/) provides estimates of employment and annual salaries for SOC codes. We used this data and matched SOC codes with their employment and salary estimates. This data was also used to weight which skills and SOC codes were more important to Army Officers than others. Skills used in fields that employ more people and have higher salaries are better for Army Officers to focus on when transitioning to civilian occupations.
