---
title: "Overview"
output: 
  html_document:
    theme: cerulean
---

Manpower planning is an essential process for all employers to get employees with the right skills and background at the right place at the right time. In an organization like the U.S. Army, which employs individuals with a variety of skills and backgrounds all over the world, manpower planning is especially important (Abdessameud, 2018; Driscoll et al, 2007; Durso and Donahue, 1995; Krupa, 2018; Gass et al., 1988; Hall, 2009; Nayar et al., 2021; Van Kerckhouven and Guerry, 2018; West, 2017; Wang, 2005).

From the perspective of an individual, it is important to match the manpower needs of an employer in order to be hired (citation). A measure of this is person-job fit. This is often measured through survey data of employees and impacts how they feel about their job and how proficient they are at that job (Huang et al, 2019). Often this survey data is unobtainable or hard to acquire, therefore we need an understanding of the skills and individual may have and of the job they are required to do. In a different way, veterans are often crowded out in job searches because they don’t know what skills they have acquired in their tenure (tenure). (Add a sentence or two to say more specifically translating military to civilian experience is difficult.)

We study the connection of Army jobs and skills acquired through civillian jobs to create a unique vector of skills associated with the Army. 

•	What skills do veterans gain in the Army?
•	What skills are gained across all Army occupations or in specific MOS?
•	What skills are necessary in the healthcare sector that are not gained by veterans?

We utilize a unique O*NET crosswalk that connects Army Military Occupation Specialty (MOS) codes with Standard Occupation Classification (SOC) codes to data from a proprietary dataset. This proprietary dataset gives us skills required for jobs through job advertisements. This research provides an overview of skills acquired in the Army which can provide information to Army Veterans on the jobs they may be best suited for and the skills they can place on their resumes in general and specifically in the healthcare industry,

