---
title: "Methods"
output: 
  html_document:
    theme: cerulean
---

### Methods

Our project methods are data linking, weighting, and network visualiiation methods. 

#### Data Linkage
We connected O*NET's crosswalk with Burning Glass data to create skill vectors for each civillian occupation and Army occupation. We then connected this data via SOC codes to BLS data which provided us average estimates of employment and salary for each SOC code, skill, and Army Occupation. This produced a dataframe of skills acquried by veterans which can be used for their resumes in their transition to civillian life. One of the big problems with transitions is the [culture differences](https://blogs.va.gov/VAntage/6603/why-can%E2%80%99t-veterans-get-jobs/) between military members and civillians. Our hope is that this data frame of skills will help guide veterans in tailoring their resumes with skills understandable by civillian employers who may not be able to translate Army occupations into skills related to their fields.

#### Data Weighting
In order to determine which skills were more useful than others we weighted skill frequencies by employment and salary. This method allows us to penalize skills that have low employment or salary estimates and reweights the importance of a skill to a veteran who is searching for a job.

#### Netwok Visualization
We visualized the connection of Army MOS codes, SOC codes, and skills using networks. For each network MOS codes are directed towards either SOC codes or skills to create large visualizations of how MOS jobs connected to each other through the ability to be hiried into certain jobs or by the skills accrued in those Army jobs. These directed networks were created in R and visualized in [Gephi](https://gephi.org/).

### Next Steps

In the future, we would like to expand our work to focus on more complicated methods of analysis. We spent the first half of the summer investigating methods for understanding Manpower Planning within the Army. Our hope is that in the future we can focus on simulation and optimization to measure how Armed Services Vocational Aptitude Battery (ASVAB) scores can translate into placement within the Army and therefore which skills a military member would acquire and then translate into probabilities of employment and salary ranges. Specifically, we could see how scores right below or right above a cut-off for a job would translate into future outcomes for a member of the Army. This regression discontinuity design is common within statistics and economics to measure how small differences can amount to large future gains in employment and monetary gain.

In the field of manpower planning we also would like to measure an Army officer's fit in their job based on the skills required for the job, which we have uncovered during this project, and the skills or test scores an officer has, which is still yet to be discovered. This future project would help the Army match officers by skills and test scores, which is an extension of this current project's goals of connected veterans to skills acquired in their jobs after placement.
