---
title: "pull_bgt_resumes"
author: "Joanna Schroeder"
date: "6/21/2021"
output: html_document
---

```{r nation-pers, message=FALSE, warning=FALSE, include=FALSE}
## USE THIS SCRIPT FOR WHOLE PERS TABLE -------------------------------------------------------

# load packages 
for (pkg in c("tidyverse", "data.table", "stringr", "stringi", "mosaic", "dplyr", "readr","gt")) {
  library(pkg, character.only = TRUE)
}

get_db_conn <-
  function(db_name = "sdad",
           db_host = "postgis1",
           db_port = "5432",
           db_user = Sys.getenv("db_usr"),
           db_pass = Sys.getenv("db_pwd")) {
    RPostgreSQL::dbConnect(
      drv = RPostgreSQL::PostgreSQL(),
      dbname = db_name,
      host = db_host,
      port = db_port,
      user = db_user,
      password = db_pass
    )
  }

con <- get_db_conn()


pers <- DBI::dbGetQuery(con, "
                        SELECT * FROM bgt_res.pers
    "
)

DBI::dbDisconnect(con)
```
 
 
 
```{r dmv-metro-pers, message=FALSE, warning=FALSE, include=FALSE}
## USE THIS SCRIPT FOR DMV METRO AREA -------------------------------------------------------

# load packages 
for (pkg in c("tidyverse", "data.table", "stringr", "stringi", "mosaic", "dplyr", "readr","gt", 'lubridate')) {
  library(pkg, character.only = TRUE)
}

get_db_conn <-
  function(db_name = "sdad",
           db_host = "postgis1",
           db_port = "5432",
           db_user = Sys.getenv("db_usr"),
           db_pass = Sys.getenv("db_pwd")) {
    RPostgreSQL::dbConnect(
      drv = RPostgreSQL::PostgreSQL(),
      dbname = db_name,
      host = db_host,
      port = db_port,
      user = db_user,
      password = db_pass
    )
  }

con <- get_db_conn()

cert <- DBI::dbGetQuery(con, "SELECT *
FROM bgt_res.cert A
JOIN bgt_res.id_msa_dc B
ON A.id = B.id"
)

ed <- DBI::dbGetQuery(con, "SELECT *
FROM bgt_res.ed A
JOIN bgt_res.id_msa_dc B
ON A.id = B.id"
)

job <- DBI::dbGetQuery(con, "SELECT *
FROM bgt_res.job A
JOIN bgt_res.id_msa_dc B
ON A.id = B.id"
)
  
pers <- DBI::dbGetQuery(con, "SELECT *
FROM bgt_res.pers A
JOIN bgt_res.id_msa_dc B
ON A.id = B.id"
)

skill <- DBI::dbGetQuery(con, "SELECT *
FROM bgt_res.skill A
JOIN bgt_res.id_msa_dc B
ON A.id = B.id"
)

DBI::dbDisconnect(con)

```


```{r nation-military}
## USE THIS SCRIPT FOR MILITARY HISTORY ----------------------------------------------------

# load packages 
for (pkg in c("tidyverse", "data.table", "stringr", "stringi", "mosaic", "dplyr", "readr","gt", 'lubridate')) {
  library(pkg, character.only = TRUE)
}

get_db_conn <-
  function(db_name = "sdad",
           db_host = "postgis1",
           db_port = "5432",
           db_user = Sys.getenv("db_usr"),
           db_pass = Sys.getenv("db_pwd")) {
    RPostgreSQL::dbConnect(
      drv = RPostgreSQL::PostgreSQL(),
      dbname = db_name,
      host = db_host,
      port = db_port,
      user = db_user,
      password = db_pass
    )
  }

con <- get_db_conn()
job <- DBI::dbGetQuery(con, paste("SELECT * FROM bgt_res.job WHERE onet LIKE '55-%'"))
DBI::dbDisconnect(con)

ids <- job %>% distinct(id) %>% pull(id)

con <- get_db_conn()

cert <- DBI::dbGetQuery(con, paste("SELECT * FROM bgt_res.cert WHERE id IN (", paste(ids, collapse = ", "), ")"))

ed <- DBI::dbGetQuery(con, paste("SELECT * FROM bgt_res.ed WHERE id IN (", paste(ids, collapse = ", "), ")"))
  
pers <- DBI::dbGetQuery(con, paste("SELECT * FROM bgt_res.pers WHERE id IN (", paste(ids, collapse = ", "), ")"))

skill <- DBI::dbGetQuery(con, paste("SELECT * FROM bgt_res.skill WHERE id IN (", paste(ids, collapse = ", "), ")"))

DBI::dbDisconnect(con)

```
